shader_type canvas_item;


uniform bool is_hit=false;
void vertex() {
	// Called for every vertex the material is visible on.
}

void fragment() {
	vec4 tex_color = texture(TEXTURE, UV);
	if (is_hit) {
		// bikin putih tapi tetap pertahankan alpha (transparansi) sprite
		COLOR = vec4(1.0, 1.0, 1.0, tex_color.a);
	} else {
		COLOR = tex_color;
	}
}

//void light() {
//	// Called for every pixel for every light affecting the CanvasItem.
//	// Uncomment to replace the default light processing function with this one.
//}
